### ISSUE TITLE
How to advance to Chapter 2?

### ISSUE THREAD

**Issue by ApolloX939** [Der1248/Castrum#2]
I think I have built everything I can for chapter 1 but I am unsure if I need to go to the island to advance to chapter 2 or what I need to do?

It would be nice to have a bit more help on a lot of spots... like I took about 10 minutes to figure out that I needed to make the tree farm to continue.

And then there is a constant annoyance of not using default tools... but not providing a recipe for them. (You do know you could make someform of extra step to convert default tools into your own right? (Its called recipes, use a default tool and perhaps make it so you add an extra item and that will be the recipe for making your tools)

**Comment by moonbard** [comment]
Did your knights do anything when you clicked "start fight"? I crafted souls, then converted to knights until I had 16, then started chapter 1 from the building with one knight and a bunch of fire. I placed them to match and exceed the enemy but nothing happened when I started the fight. I quit to OS as backing out of that room removes all the knights (much to my chagrin the first time I tried).

**Comment by ApolloX939** [comment]
Oh, ok... I only made around 4 knights. Guess I just need to make the rest of them to continue.

**Comment by Der1248** [comment]
I havend worked on a guide through the game. But there is more help planned before this game will not be a WIP game anymore. The fight system in also not finished yet.
